apiVersion: v1
kind: Service
metadata:
  name: jerry-app
spec:
  selector:
    app: jerry-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9999
      nodePort: 30000
  type: NodePort

