apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: my-namespace
  labels:
    app: redis
spec:
  type: NodePort
  ports:
    - name: tcp
      port: 6379
  selector:
    app: redis